### ISSUE TITLE
USER STORY: User profile

### ISSUE THREAD

**Issue by EvitaKnits** [Vasileios20/infinity-hub#26]
As  a user I want to have my own profile page so I can see what I'm set to

**Elements**: 
- User's life stage and neurodiversity setting
- (A link to their specific forum - this will be programmed in the front end, by retrieving the user's stored NC and lifestage, and applying these as filters to the data determined when accessing the forum using the filters based on the users values in the neurodiversity and lifestage fields)
- A section about contacting support to change their settings and a link to the contact page (front-end)

**Acceptance Criteria**:
- User profile model created in Django (must include neurodiversity and lifestage - as per Evita comment, looks like these need many to many relationships to a lookup table, as people may have more than 1 ND)
- (May need to split out this user story into component task issues)
- 

Tasks:
- [x] Task  Agree user profile model fields
- [x] Task  Create user profile app & associated model(s) in Django (extension of AllAuth)

**Comment by DeeMcCart** [comment]
Done.  The screen is not pretty and we may need to reconsider some of the fields but its fine
