### ISSUE TITLE
Bug: Homepage layout issues

### ISSUE THREAD

**Issue by EvitaKnits** [Vasileios20/infinity-hub#61]
1. The circle shows: Signup/login should be one item? And maybe a button so its a clear CTA?
2. The arrows show: the spacing needs evening out
3. The square shows: the middle card is bigger than the other two **(DMcC 25/04/24 Yep that's me, its data related, I have chosen wrong-sized images some with whitespace so will resolve this)**

**Comment by EvitaKnits** [comment]
![Image](https://github.com/Vasileios20/infinity-hub/assets/12150741/1fd83682-b3fe-426f-847e-77b77ee191ed)

**Comment by violaberg** [comment]
_1. The circle shows: Signup/login should be one item? And maybe a button so its a clear CTA?_

It can't be one item/ button as each links to different pages. I'll make them buttons. Same as button in the middle should maybe say 'Join community' or something like that and link to sign up page. I'll assign it myself if everyone agrees
