### ISSUE TITLE
Bug: About page layout issues

### ISSUE THREAD

**Issue by EvitaKnits** [Vasileios20/infinity-hub#62]
1. Same spacing issue as on homepage - everything bunched up at the top. 
2. Two columns of team members would look better
3. There is section called 'Further Questions:' at the bottom that leads into nothing.

**Comment by violaberg** [comment]
About Us page styled

**Comment by EvitaKnits** [comment]
Don't forget to spread out the content (point 1 above)

**Comment by Katherine-Holland** [comment]
Need to add in answers to FAQ and add LinkedIn for Eddie.
